[package]
name = "rustywatch"
version = "0.1.0"
edition = "2021"

[dependencies]

[package.metadata.nix]
build = true
app = true
library = false
systems = [
    "aarch64-linux",
    "aarch64-darwin",
    "i686-linux",
    "x86_64-darwin",
    "x86_64-linux",
]

# EOF #
